### ISSUE TITLE
Non Merci ne bloque pas les numéros indésirables

### ISSUE THREAD

**Issue by farvardin** [alex14fr/NonMerci#1]
salut, 

j'ai installé Non Merci sur lineageOS 11, il semble correctement installé mais ne bloque apparemment pas les numéros indésirables (par exemple ce 04 24). Est-ce que le fait que ça indique +33 4 24 change quelque chose ? 

![Screenshot_20231017-121537_Trebuchet](https://github.com/alex14fr/NonMerci/assets/477243/34841964-ed62-4e14-a127-311f28e536a6)

![Screenshot_20231017-121322_Trebuchet](https://github.com/alex14fr/NonMerci/assets/477243/b533fa8f-77b8-4cf7-8dfa-c9a4684ea675)

**Comment by alex14fr** [comment]
Bonjour,
J'ai aussi testé sur Android 11 (donc LineageOS 18, LineageOS 11 c'est Android 4.4 je crois donc assez vieux et ne collant pas à tes screenshots) et ca marche en bloquant 04 24, même s'il y a +33 4 24 dans le journal d'appels comme toi.
Du coup je ne sais pas trop :-)
Si tu veux tester en mettant les versions avec +33424, etc et 33424 dans le tableau blockedPrefixes du fichier Receiver.java et en recompilant (il faut un JDK assez ancien et certains outils d'Android Studio); si pas possible je le fais et je mets un apk à tester.

**Comment by alex14fr** [comment]
PS. Les nums indésirables peuvent apparaitre dans le journal d'appels, ce qui est bloqué c'est la sonnerie (hors signal d'appel)

**Comment by farvardin** [comment]
oui tu as raison pour android 11, j'ai confondu...

j'ai tout le temps la sonnerie coupée, donc je ne vois pas forcément la différence, mais effectivement je vois les numéros dans le journal d'appel. 

Par contre, pendant les appels, même s'il n'y a pas de sonnerie, l'interface d'appel en plein écran vient remplacer le programme en cours. L'autre jour j'ai eu un tel appel pendant que j'utilisais une autre application, et c'était perturbant (interface de sonnerie en plein écran). Mais j'imagine que cela n'est pas possible de faire autrement et que cela dépasse les capacités de cette application...

**Comment by farvardin** [comment]
@alex14fr pour une fois j'avais laissé mon tél avec la sonnerie, et tout à l'heure je viens d'avoir un appel (avec sonnerie donc) d'un "02 70" alors qu'il aurait dû être bloqué. C'était bien indiqué "02 70" lors de l'appel, et ensuite ça marquait "+33 2 70" dans le journal d'appel.

**Comment by farvardin** [comment]
pour comparer, je viens d'installer NoPhoneSpam, j'ai enregistré un numéro dans la liste noire, l'ai exportée puis modifiée depuis mon PC pour rajouter tous les numéros problématiques. Il suffit ensuite d'avoir un fichier nommé ``NoPhoneSpam_blacklist.txt`` à la racine du système (là où l'application l'a déjà initialement exportée) avec ce contenu : 

```
+33162%: FRspam01
+33163%: FRspam02
+33270%: FRspam03
+33271%: FRspam04
+33377%: FRspam05
+33378%: FRspam06
+33424%: FRspam07
+33425%: FRspam08
+33568%: FRspam09
+33569%: FRspam10
+33948%: FRspam11
+33949%: FRspam12
+339475%: FRspam13
+339476%: FRspam14
+339477%: FRspam15
+339478%: FRspam16
+339479%: FRspam17
```

**Comment by farvardin** [comment]
ça n'a pas traîné, je venais à peine de mettre ça en place que j'ai reçu un appel d'un "0424", et NoPhoneSpam l'a bien bloqué, ça m'a fait une notification de l'app (sonore, mais on peut la désactiver), et pas de sonnerie ni d'app téléphonique en plein écran.

**Comment by alex14fr** [comment]
Merci pour ton retour.
